"""add note for admins

Revision ID: 116a916f1bcb
Revises: 20e2a5cf1e40
Create Date: 2026-02-22 15:43:09.675973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116a916f1bcb'
down_revision = '20e2a5cf1e40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
