"""add verifyPeerCertByName to hosts

Revision ID: 20e2a5cf1e40
Revises: 2a1176f0c666
Create Date: 2026-02-15 19:33:07.307708

"""
from alembic import op
import sqlalchemy as sa
import app.db.compiles_types as ct


# revision identifiers, used by Alembic.
revision = '20e2a5cf1e40'
down_revision = '2a1176f0c666'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.alter_column(
            'pinnedPeerCertSha256',
            existing_type=sa.String(length=128),
            new_column_name='pinned_peer_cert_sha256',
            existing_nullable=True,
        )
        batch_op.add_column(sa.Column('verify_peer_cert_by_name', ct.StringArray(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.alter_column(
            'pinned_peer_cert_sha256',
            existing_type=sa.VARCHAR(length=128),
            new_column_name='pinnedPeerCertSha256',
            existing_nullable=True,
        )
        batch_op.drop_column('verify_peer_cert_by_name')

    # ### end Alembic commands ###
