"""separate nodes config

Revision ID: 4e66033a2b9b
Revises: 1ccf7b18b283
Create Date: 2025-04-08 17:39:03.984285

"""

from functools import cached_property
from alembic import op
import sqlalchemy as sa
import commentjson
from datetime import datetime as dt, timezone as tz
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

from app.core.xray import XRayConfig


# revision identifiers, used by Alembic.
revision = "4e66033a2b9b"
down_revision = "1ccf7b18b283"
branch_labels = None
depends_on = None


class MigrationSettings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    xray_json: str = Field(default="./xray_config.json", validation_alias="XRAY_JSON")
    xray_fallbacks_inbound_tags_raw: str = Field(default="", validation_alias="XRAY_FALLBACKS_INBOUND_TAG")
    xray_exclude_inbound_tags_raw: str = Field(default="", validation_alias="XRAY_EXCLUDE_INBOUND_TAGS")

    @cached_property
    def xray_fallbacks_inbound_tags(self) -> list[str]:
        return [tag.strip() for tag in self.xray_fallbacks_inbound_tags_raw.split(",") if tag.strip()]

    @cached_property
    def xray_exclude_inbound_tags(self) -> list[str]:
        return self.xray_exclude_inbound_tags_raw.split()


migration_settings = MigrationSettings()


base_xray = {
    "policy": {"levels": {"0": {"statsUserOnline": True}}},
    "log": {"loglevel": "warning"},
    "inbounds": [
        {
            "tag": "Shadowsocks TCP",
            "listen": "0.0.0.0",
            "port": 1080,
            "protocol": "shadowsocks",
            "settings": {"clients": [], "network": "tcp,udp"},
        }
    ],
    "outbounds": [{"protocol": "freedom", "tag": "DIRECT"}, {"protocol": "blackhole", "tag": "BLOCK"}],
    "routing": {"rules": [{"ip": ["geoip:private"], "outboundTag": "BLOCK", "type": "field"}]},
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("exclude_inbound_tags", sa.String(length=2048), nullable=True),
        sa.Column("fallbacks_inbound_tags", sa.String(length=2048), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("nodes", sa.Column("core_config_id", sa.Integer(), nullable=True))
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.create_foreign_key("nodes_ibfk_1", "core_configs", ["core_config_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###
    try:
        with open(migration_settings.xray_json, "r") as file:
            config = commentjson.loads(file.read())

        XRayConfig(
            config,
            migration_settings.xray_exclude_inbound_tags,
            migration_settings.xray_fallbacks_inbound_tags,
        )
    except Exception:
        config = base_xray

    op.bulk_insert(
        sa.table(
            "core_configs",
            sa.Column("created_at", sa.DateTime),
            sa.Column("name", sa.String),
            sa.Column("config", sa.JSON),
            sa.Column("exclude_inbound_tags", sa.String),
            sa.Column("fallbacks_inbound_tags", sa.String),
        ),
        [
            {
                "created_at": dt.now(tz.utc).replace(tzinfo=None),
                "name": "Default Core Config",
                "config": config,
                "exclude_inbound_tags": ",".join(migration_settings.xray_exclude_inbound_tags),
                "fallbacks_inbound_tags": ",".join(migration_settings.xray_fallbacks_inbound_tags),
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("nodes_ibfk_1", "nodes", type_="foreignkey")
    op.drop_column("nodes", "core_config_id")
    op.drop_table("core_configs")
    # ### end Alembic commands ###
