"""add pinnedPeerCertSha256 to hosts

Revision ID: 5213b80a795c
Revises: 7b5e1623c19a
Create Date: 2026-02-11 22:34:07.678777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5213b80a795c'
down_revision = '7b5e1623c19a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'apscheduler_jobs' in inspector.get_table_names():
        index_names = {idx.get('name') for idx in inspector.get_indexes('apscheduler_jobs')}
        preferred_name = op.f('ix_apscheduler_jobs_next_run_time')
        if preferred_name in index_names:
            op.drop_index(preferred_name, table_name='apscheduler_jobs')
        elif 'ix_apscheduler_jobs_next_run_time' in index_names:
            op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
        op.drop_table('apscheduler_jobs')
    op.add_column('hosts', sa.Column('pinnedPeerCertSha256', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'pinnedPeerCertSha256')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
