"""admin_rbac_roles

Revision ID: 66c38b8a687a
Revises: f02194c811d6
Create Date: 2026-05-17 14:32:55.004013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
import app.db.compiles_types

# revision identifiers, used by Alembic.
revision = '66c38b8a687a'
down_revision = 'f02194c811d6'
branch_labels = None
depends_on = None

OWNER_PERMISSIONS = {
    "users": {"create": True, "read": {"scope": 2}, "read_simple": {"scope": 2}, "update": {"scope": 2}, "delete": {"scope": 2}, "reset_usage": {"scope": 2}, "revoke_sub": {"scope": 2}, "set_owner": True, "activate_next_plan": {"scope": 2}},
    "admins": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True, "reset_usage": True},
    "nodes": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True, "reconnect": True, "update_core": True, "logs": True, "stats": True},
    "groups": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True},
    "hosts": {"create": True, "read": True, "update": True},
    "templates": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True},
    "client_templates": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True},
    "cores": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True},
    "settings": {"read": True, "read_general": True, "update": True},
    "system": {"read": True},
    "hwids": {"read": True, "delete": True},
    "admin_roles": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True},
}
ADMINISTRATOR_PERMISSIONS = {
    "users": {"create": True, "read": {"scope": 2}, "read_simple": {"scope": 2}, "update": {"scope": 2}, "delete": {"scope": 2}, "reset_usage": {"scope": 2}, "revoke_sub": {"scope": 2}, "set_owner": True, "activate_next_plan": {"scope": 2}},
    "admins": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True, "reset_usage": True},
    "nodes": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True, "reconnect": True, "update_core": True, "logs": True, "stats": True},
    "groups": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True},
    "hosts": {"create": True, "read": True, "update": True},
    "templates": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True},
    "client_templates": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True},
    "cores": {"create": True, "read": True, "read_simple": True, "update": True, "delete": True},
    "settings": {"read": True, "read_general": True, "update": True},
    "system": {"read": True},
    "hwids": {"read": True, "delete": True},
    "admin_roles": {"read": True, "read_simple": True},
}
OPERATOR_PERMISSIONS = {
    "users": {"create": True, "read": {"scope": 1}, "read_simple": {"scope": 1}, "update": {"scope": 1}, "delete": {"scope": 1}, "reset_usage": {"scope": 1}, "revoke_sub": {"scope": 1}, "set_owner": None, "activate_next_plan": {"scope": 1}},
    "groups": {"create": False, "read": False, "read_simple": True, "update": False, "delete": False},
    "templates": {"create": False, "read": True, "read_simple": True, "update": False, "delete": False},
    "system": {"read": True},
    "settings": {"read": False, "read_general": True, "update": False},
    "hwids": {"read": True, "delete": True},
}
DEFAULT_LIMITS = {"max_users": None, "data_limit_min": None, "data_limit_max": None, "expire_min": None, "expire_max": None, "min_hwid_per_user": None, "max_hwid_per_user": None}
DEFAULT_FEATURES = {"can_use_reset_strategy": True, "can_use_next_plan": True}
DEFAULT_ACCESS = {"require_template": False, "allowed_template_ids": None, "allowed_group_ids": None}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_roles',
    sa.Column('id', app.db.compiles_types.SqliteCompatibleBigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_owner', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('permissions', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('limits', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('access', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_admin_roles_name'))
    )

    # Seed default roles
    from datetime import datetime
    now = datetime.utcnow()  # naive UTC — compatible with all DBs

    admin_roles_table = sa.table(
        'admin_roles',
        sa.column('name', sa.String),
        sa.column('is_owner', sa.Boolean),
        sa.column('permissions', sa.JSON),
        sa.column('limits', sa.JSON),
        sa.column('features', sa.JSON),
        sa.column('access', sa.JSON),
        sa.column('created_at', sa.DateTime),
    )
    op.bulk_insert(admin_roles_table, [
        {"name": "owner",         "is_owner": True,  "permissions": OWNER_PERMISSIONS,         "limits": DEFAULT_LIMITS, "features": DEFAULT_FEATURES, "access": DEFAULT_ACCESS, "created_at": now},
        {"name": "administrator", "is_owner": False, "permissions": ADMINISTRATOR_PERMISSIONS, "limits": DEFAULT_LIMITS, "features": DEFAULT_FEATURES, "access": DEFAULT_ACCESS, "created_at": now},
        {"name": "operator",      "is_owner": False, "permissions": OPERATOR_PERMISSIONS,      "limits": DEFAULT_LIMITS, "features": DEFAULT_FEATURES, "access": DEFAULT_ACCESS, "created_at": now},
    ])

    op.create_table('temp_keys',
    sa.Column('key', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_temp_keys'))
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', app.db.compiles_types.SqliteCompatibleBigInteger(), nullable=True))
        batch_op.add_column(sa.Column('permission_overrides', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True))
    # Backfill: if there is exactly one sudo admin, make it owner. Otherwise keep legacy behavior:
    # is_sudo=true -> administrator (id=2), is_sudo=false -> operator (id=3).
    conn = op.get_bind()
    dialect = conn.dialect.name
    if dialect == "postgresql":
        sudo_count = conn.execute(sa.text("SELECT COUNT(*) FROM admins WHERE is_sudo = true")).scalar()
        if sudo_count == 1:
            conn.execute(sa.text("UPDATE admins SET role_id = 1 WHERE is_sudo = true"))
        else:
            conn.execute(sa.text("UPDATE admins SET role_id = 2 WHERE is_sudo = true"))
        conn.execute(sa.text("UPDATE admins SET role_id = 3 WHERE is_sudo = false OR role_id IS NULL"))
    else:
        sudo_count = conn.execute(sa.text("SELECT COUNT(*) FROM admins WHERE is_sudo = 1")).scalar()
        if sudo_count == 1:
            conn.execute(sa.text("UPDATE admins SET role_id = 1 WHERE is_sudo = 1"))
        else:
            conn.execute(sa.text("UPDATE admins SET role_id = 2 WHERE is_sudo = 1"))
        conn.execute(sa.text("UPDATE admins SET role_id = 3 WHERE is_sudo = 0 OR role_id IS NULL"))

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('role_id', existing_type=app.db.compiles_types.SqliteCompatibleBigInteger(), nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_admins_role_id_admin_roles'), 'admin_roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_admins_role_id_admin_roles'), type_='foreignkey')
        batch_op.drop_column('permission_overrides')
        batch_op.drop_column('role_id')

    op.drop_table('temp_keys')
    op.drop_table('admin_roles')
    # ### end Alembic commands ###
