"""add cipherSuites to hosts

Revision ID: 6a9fff8290b9
Revises: fb32155473c1
Create Date: 2026-08-06 16:35:31.165559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9fff8290b9'
down_revision = 'fb32155473c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cipher_suites', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_column('cipher_suites')

    # ### end Alembic commands ###
