"""admin notification enable

Revision ID: 797420faec8d
Revises: 5021dbccc95f
Create Date: 2025-11-04 18:40:23.363359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = '797420faec8d'
down_revision = '5021dbccc95f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dialect_name = bind.dialect.name

    if dialect_name == "postgresql":
        from sqlalchemy.dialects.postgresql import JSONB

        json_type = JSONB(none_as_null=True)
    else:
        json_type = sa.JSON()

    op.add_column('admins', sa.Column('notification_enable', json_type, nullable=True))

    # Populate existing admins with the default notification preferences.
    admin_exists = bind.execute(sa.text("SELECT 1 FROM admins LIMIT 1")).first()

    if admin_exists:
        default_notification = {
            "create": True,
            "modify": True,
            "delete": True,
            "status_change": True,
            "reset_data_usage": True,
            "data_reset_by_next": True,
            "subscription_revoked": True,
        }
        admins_table = table(
            'admins',
            column('notification_enable', json_type),
        )
        bind.execute(
            admins_table.update()
            .where(admins_table.c.notification_enable.is_(None))
            .values(notification_enable=default_notification)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'notification_enable')
    # ### end Alembic commands ###
