"""Vless Route

Revision ID: 7b5e1623c19a
Revises: ee97c01bfbaf
Create Date: 2026-02-06 15:41:16.979955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5e1623c19a'
down_revision = 'ee97c01bfbaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('vless_route', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'vless_route')
    # ### end Alembic commands ###
