"""remove gather logs and max logs columns

Revision ID: 99076844dee6
Revises: 2dffd851d87c
Create Date: 2025-11-14 17:19:08.568000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99076844dee6'
down_revision = '2dffd851d87c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'gather_logs')
    op.drop_column('nodes', 'max_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('max_logs', sa.BigInteger(), server_default=sa.text('1000'), nullable=False))
    op.add_column('nodes', sa.Column('gather_logs', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###

