"""node default timeout

Revision ID: a0a1125e46b1
Revises: 99076844dee6
Create Date: 2025-11-19 17:53:48.835236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a1125e46b1'
down_revision = '99076844dee6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('default_timeout', sa.Integer(), server_default=sa.text('(10)'), nullable=False))
    op.add_column('nodes', sa.Column('internal_timeout', sa.Integer(), server_default=sa.text('(15)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'internal_timeout')
    op.drop_column('nodes', 'default_timeout')
    # ### end Alembic commands ###
