"""node proxy url

Revision ID: af2d644dda44
Revises: b7d9e1a2c3f4
Create Date: 2026-05-02 00:16:30.427468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2d644dda44'
down_revision = 'b7d9e1a2c3f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nodes",
        sa.Column("proxy_url", sa.String(length=256), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_column('proxy_url')

    # ### end Alembic commands ###
