"""add api port column

Revision ID: ee97c01bfbaf
Revises: a0a1125e46b1
Create Date: 2025-11-27 09:11:08.524305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee97c01bfbaf'
down_revision = 'a0a1125e46b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('api_port', sa.Integer(), server_default='62051', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'api_port')
    # ### end Alembic commands ###
