"""add final_mask_settings to hosts table

Revision ID: f976bfcf4738
Revises: b6c9d0e1f2a3
Create Date: 2026-05-02 13:46:21.008567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f976bfcf4738'
down_revision = 'b6c9d0e1f2a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_mask_settings', sa.JSON(none_as_null=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_column('final_mask_settings')

    # ### end Alembic commands ###
