name: Telegram Notification

on:
  push:
    branches:
      - main
      - dev
  pull_request_target:
    types: [opened, closed]

jobs:
  notify:
    uses: PasarGuard/.github/.github/workflows/telegram-notify.yml@main
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    with:
      telegram_targets: ${{ vars.TELEGRAM_TARGETS }}
